try:
    number1 = 10
    number2 = 5
    print(number1 + number2)
except Exception as e:
    print(e)